version: '2'

services:
  db:
    image: postgres
  web:
    build:
      context: ./lxs
      dockerfile: Dockerfile
    command: bash runserver.sh
    volumes:
      - ./lxs:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

